### ISSUE TITLE
AWS resources panic lyra after creation

### ISSUE THREAD

**Issue by ahpook** [lyraproj/lyra#171]
**Describe the bug**
I am reliably able to panic `lyra controller` by changing the state of AWS resources 'under the hood'.

**To Reproduce**
1. register the CRD with kubernetes and start lyra in controller mode
2. submit the `vpc-workflow` to the cluster
3. from the amazon console, delete one of the created resources

**Expected behavior**
i'd expect lyra to re-create the deleted resource, or at least handle the error gracefully if it cannot.

**Logs**

```
panic: invocation of Aws::VPCHandler delete failed: EVAL_GO_FUNCTION_ERROR Go function Delete returned error 'DependencyViolation:
The vpc 'vpc-0ac28d1dcdfcabd04' has dependencies and cannot be deleted.
        status code: 400, request id: f0e7a065-7ac1-4bad-a943-83ca89878e3a'

goroutine 286 [running]:
github.com/lyraproj/servicesdk/grpc.(*Client).Invoke(0xc0001921f0, 0x27086e0, 0xc002291720, 0xc000735750, 0xf, 0x2442653, 0x6, 0xc000965550, 0x1, 0x1, ...)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/servicesdk@v0.0.0-20190227091652-cbae88715c21/grpc/client.go:59 +0x5f8
github.com/lyraproj/wfe/service.ApplyState(0x27086e0, 0xc002291720, 0x26ed7e0, 0xc002606000, 0x27103e0, 0xc001210440, 0x26c0801, 0xc001210440)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190220162440-1888b39c9eca/service/crud.go:110 +0xd7e
github.com/lyraproj/wfe/wfe.(*resource).Run(0xc002606000, 0x27086e0, 0xc002291720, 0x27103e0, 0xc001210440, 0x26e2f00, 0xc001494b40)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190220162440-1888b39c9eca/wfe/resource.go:54 +0x5f
github.com/lyraproj/wfe/wfe.(*workflowEngine).runActivity(0xc0004b9380, 0x27086e0, 0xc002291720, 0xc002724810)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190220162440-1888b39c9eca/wfe/workflowengine.go:416 +0x381
github.com/lyraproj/wfe/wfe.(*workflowEngine).activityWorker(0xc0004b9380, 0x27086e0, 0xc002291720, 0x6)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190220162440-1888b39c9eca/wfe/workflowengine.go:390 +0x8e
github.com/lyraproj/wfe/wfe.(*workflowEngine).Run.func2(0x27086e0, 0xc002291720)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190220162440-1888b39c9eca/wfe/workflowengine.go:316 +0x4a
github.com/lyraproj/puppet-evaluator/eval.Fork.func1(0x27086e0, 0xc0006e1540, 0xc0013067c0)
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/puppet-evaluator@v0.0.0-20190304221938-dfca410f5e9b/eval/eval.go:37 +0xb7
created by github.com/lyraproj/puppet-evaluator/eval.Fork
        /Users/eric/Sandbox/go/pkg/mod/github.com/lyraproj/puppet-evaluator@v0.0.0-20190304221938-dfca410f5e9b/eval/eval.go:32 +0x53
```
**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.1]
 - Version/Build number [e.g. 0.0.1, f61edcc]
 - Cloud target [e.g. AWS, GCP]

**Additional context**

**Comment by scottyw** [comment]
Possible relationship with #160

**Comment by scottyw** [comment]
I suspect that this isn't a controller specific thing and that you might run into the same issue with the cli too.

**Comment by scottyw** [comment]
We've been able to recreate by running the "aws_vpc_yaml" workflow twice consecutively on the command line without making any changes to the real-world resources. Current theory is that Lyra erroneously trying to perform an update when none is necessary. The AWS plugin does not have update support and so Lyra falls back to delete-and-recreate, the delete half of whiich causes this dependency violation.

**Comment by markfuller** [comment]
<details>
  <summary>Second time running `build/lyra apply  aws_vpc_yaml --debug`</summary>
  
```sh
2019-03-13T15:13:27.176Z [DEBUG] lyra.loader: checking './plugins' for '*.ll' files ...
2019-03-13T15:13:27.177Z [DEBUG] lyra.loader: found 1 files
2019-03-13T15:13:27.177Z [DEBUG] lyra.loader: checking './build' for '*.ll' files ...
2019-03-13T15:13:27.177Z [DEBUG] lyra.loader: found 0 files
2019-03-13T15:13:27.177Z [DEBUG] lyra.loader: reading Lyra Link: file=plugins/ts-samples.ll
2019-03-13T15:13:27.177Z [DEBUG] lyra: starting plugin: path=/usr/local/bin/node args=[node, examples/ts-samples/dist/vpc_with_subnet.js]
2019-03-13T15:13:27.185Z [DEBUG] lyra: plugin started: path=/usr/local/bin/node pid=96717
2019-03-13T15:13:27.185Z [DEBUG] lyra: waiting for RPC address: path=/usr/local/bin/node
2019-03-13T15:13:27.452Z [DEBUG] lyra.node: module.js:491
2019-03-13T15:13:27.452Z [DEBUG] lyra.node:     throw err;
2019-03-13T15:13:27.452Z [DEBUG] lyra.node:     ^
2019-03-13T15:13:27.452Z [DEBUG] lyra.node: 
2019-03-13T15:13:27.452Z [DEBUG] lyra.node: Error: Cannot find module '/Users/Mark/code/lyra/examples/ts-samples/dist/vpc_with_subnet.js'
2019-03-13T15:13:27.452Z [DEBUG] lyra.node:     at Function.Module._resolveFilename (module.js:489:15)
2019-03-13T15:13:27.453Z [DEBUG] lyra.node:     at Function.Module._load (module.js:439:25)
2019-03-13T15:13:27.453Z [DEBUG] lyra.node:     at Function.Module.runMain (module.js:609:10)
2019-03-13T15:13:27.453Z [DEBUG] lyra.node:     at startup (bootstrap_node.js:158:16)
2019-03-13T15:13:27.453Z [DEBUG] lyra.node:     at bootstrap_node.js:598:3
2019-03-13T15:13:27.455Z [ERROR] lyra: error creating GRPC client: error="Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol."
2019-03-13T15:13:27.455Z [DEBUG] lyra: plugin process exited: path=/usr/local/bin/node pid=96717 error="exit status 1"
2019-03-13T15:13:27.455Z [ERROR] lyra.loader: failed to load Lyra Link: file=plugins/ts-samples.ll err="Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol."
2019-03-13T15:13:27.456Z [DEBUG] lyra: all plugins loaded
2019-03-13T15:13:27.456Z [DEBUG] lyra: calling apply
2019-03-13T15:13:27.456Z [DEBUG] lyra: configuring scope
2019-03-13T15:13:27.456Z [DEBUG] lyra: applying: activityID=aws_vpc_yaml
2019-03-13T15:13:27.457Z [DEBUG] lyra: creating activity: style=workflow
2019-03-13T15:13:27.457Z [DEBUG] lyra: creating activity: style=resource
2019-03-13T15:13:27.457Z [DEBUG] lyra: creating activity: style=resource
2019-03-13T15:13:27.457Z [DEBUG] lyra: creating activity: style=resource
panic: invocation of Aws::VPCHandler delete failed: EVAL_GO_FUNCTION_ERROR Go function Delete returned error 'DependencyViolation: The vpc 'vpc-0b539d1cd9fce08e3' has dependencies and cannot be deleted.
	status code: 400, request id: 796546c4-8f3d-421e-81d1-944f3f2a67b1'  

goroutine 203 [running]:
github.com/lyraproj/servicesdk/grpc.(*Client).Invoke(0xc00015c9d0, 0x254a080, 0xc001e804e0, 0xc0001c4ff0, 0xf, 0x2341f76, 0x6, 0xc0010207d0, 0x1, 0x1, ...)
	/Users/Mark/code/servicesdk/grpc/client.go:63 +0x643
github.com/lyraproj/wfe/service.ApplyState(0x254a080, 0xc001e804e0, 0x2540b20, 0xc0025aa1b0, 0x2556380, 0xc00161bd00, 0x252a501, 0xc00161bd00)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/service/crud.go:109 +0xdd3
github.com/lyraproj/wfe/wfe.(*resource).Run(0xc0025aa1b0, 0x254a080, 0xc001e804e0, 0x2556380, 0xc00161bd00, 0x2539ca0, 0xc0014a8980)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/resource.go:55 +0x5f
github.com/lyraproj/wfe/wfe.(*workflowEngine).runActivity(0xc001f0e7e0, 0x254a080, 0xc001e804e0, 0xc0013dc000)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/workflowengine.go:417 +0x3da
github.com/lyraproj/wfe/wfe.(*workflowEngine).activityWorker(0xc001f0e7e0, 0x254a080, 0xc001e804e0, 0x6)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/workflowengine.go:391 +0x91
github.com/lyraproj/wfe/wfe.(*workflowEngine).Run.func2(0x254a080, 0xc001e804e0)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/workflowengine.go:317 +0x4a
github.com/lyraproj/pcore/px.Fork.func1(0x254a080, 0xc0003692c0, 0xc001258000)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190313112821-30e7bb7af627/px/context.go:166 +0xb7
created by github.com/lyraproj/pcore/px.Fork
	/Users/Mark/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190313112821-30e7bb7af627/px/context.go:161 +0x53

```
</details>

**Comment by markfuller** [comment]
Seems like the Equals method is being invoked on a slice of `[]px.Value` objects rather than a single `px.Value`

Something to do with type conversion?

<details>
  <summary>Changes to pcore to add logging</summary>

```sh
➜  pcore git:(master) ✗ git --no-pager diff
diff --git a/px/equality.go b/px/equality.go
index 251d662..a815445 100644
--- a/px/equality.go
+++ b/px/equality.go
@@ -1,6 +1,10 @@
 package px

-import "reflect"
+import (
+	"github.com/davecgh/go-spew/spew"
+	"github.com/hashicorp/go-hclog"
+	"reflect"
+)

 type (
 	visit struct {
@@ -60,7 +64,13 @@ func Equals(a interface{}, b interface{}, g Guard) bool {
 		bs, ok := b.(string)
 		return ok && a == bs
 	default:
-		return reflect.DeepEqual(a, b)
+		r := reflect.DeepEqual(a, b)
+		if !r {
+			spewA := spew.Sdump(a)
+			spewB := spew.Sdump(b)
+			hclog.Default().Debug("Equals check failed", "a", spewA, "b", spewB, "g", g)
+		}
+		return r
 	}
 }
```

Note the type of a and b is `[]px.Value` not `px.Value`

<details>
<summary>Output</summary>

```sh
2019-03-14T14:31:19.625Z [DEBUG] lyra: applying: activityID=aws_example
2019-03-14T14:31:19.627Z [DEBUG] lyra: creating activity: style=workflow
2019-03-14T14:31:19.627Z [DEBUG] lyra: creating activity: style=resource
2019-03-14T14:31:19.627Z [DEBUG] lyra: creating activity: style=resource
2019-03-14T14:31:19.631Z [DEBUG] lyra.goplugin-aws: 2019-03-14T14:31:19.631Z [DEBUG] Reading VPC: externalID=vpc-0cff5ff0e86f2d2e6
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws: 2019-03-14T14:31:20.119Z [DEBUG] Completed VPC read: actual="(*ec2.Vpc)(0xc000423880)({
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   CidrBlock: "192.168.0.0/16",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   CidrBlockAssociationSet: [{
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       AssociationId: "vpc-cidr-assoc-01a4ea4bfb79535a8",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       CidrBlock: "192.168.0.0/16",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       CidrBlockState: {
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:         State: "associated"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       }
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     }],
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   DhcpOptionsId: "dopt-678a1403",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   InstanceTenancy: "default",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   IsDefault: false,
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   OwnerId: "747277873297",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   State: "available",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   Tags: [
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     {
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Key: "lifetime",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Value: "1h"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     },
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     {
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Key: "created_by",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Value: "lyra"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     },
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     {
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Key: "Name",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Value: "lyra-sample"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     },
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     {
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Key: "department",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Value: "engineering"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     },
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     {
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Key: "project",
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:       Value: "incubator"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:     }
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   ],
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws:   VpcId: "vpc-0cff5ff0e86f2d2e6"
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws: })
2019-03-14T14:31:20.119Z [DEBUG] lyra.goplugin-aws: " err=<nil>
2019-03-14T14:31:20.120Z [DEBUG] lyra: Equals check failed: a="([]px.Value) (len=7 cap=10) {
 (types.booleanValue) false,
 (types.stringValue) (len=14) 192.168.0.0/16,
 (types.booleanValue) false,
 (types.booleanValue) false,
 (*types.Hash)(0xc001e6d640)({'Name' => 'lyra-sample', 'created_by' => 'lyra', 'department' => 'engineering', 'lifetime' => '1h', 'project' => 'incubator'}),
 (types.booleanValue) false,
 (types.stringValue) (len=9) available
}
" b="([]px.Value) (len=10 cap=10) {
 (types.booleanValue) false,
 (types.stringValue) (len=14) 192.168.0.0/16,
 (types.booleanValue) false,
 (types.booleanValue) false,
 (*types.Hash)(0xc001e56940)({'Name' => 'lyra-sample', 'created_by' => 'lyra', 'department' => 'engineering', 'lifetime' => '1h', 'project' => 'incubator'}),
 (types.booleanValue) false,
 (types.stringValue) (len=9) available,
 (types.stringValue) (len=7) default,
 (types.stringValue) (len=21) vpc-0cff5ff0e86f2d2e6,
 (types.stringValue) (len=13) dopt-678a1403
}
" g=map[]
2019-03-14T14:31:20.120Z [DEBUG] lyra.goplugin-aws: 2019-03-14T14:31:20.120Z [DEBUG] Deleting VPC: externalID=vpc-0cff5ff0e86f2d2e6
2019-03-14T14:31:20.196Z [DEBUG] lyra.goplugin-aws: 2019-03-14T14:31:20.196Z [DEBUG] Error deleting VPC ec2 service client for VPC Delete: externalID=vpc-0cff5ff0e86f2d2e6 error="DependencyViolation: The vpc 'vpc-0cff5ff0e86f2d2e6' has dependencies and cannot be deleted.
2019-03-14T14:31:20.196Z [DEBUG] lyra.goplugin-aws: 	status code: 400, request id: 6f510f08-af23-42a0-a126-0ee6624eff0c"
panic: invocation of Aws::VPCHandler delete failed: EVAL_GO_FUNCTION_ERROR Go function Delete returned error 'DependencyViolation: The vpc 'vpc-0cff5ff0e86f2d2e6' has dependencies and cannot be deleted.
	status code: 400, request id: 6f510f08-af23-42a0-a126-0ee6624eff0c'  

goroutine 199 [running]:
github.com/lyraproj/servicesdk/grpc.(*Client).Invoke(0xc000212530, 0x25555c0, 0xc003213800, 0xc0002cec90, 0xf, 0x234c7dc, 0x6, 0xc000230e30, 0x1, 0x1, ...)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/servicesdk@v0.0.0-20190313114433-a66d98e28e69/grpc/client.go:63 +0x643
github.com/lyraproj/wfe/service.ApplyState(0x25555c0, 0xc003213800, 0x254c060, 0xc002123200, 0x25618c0, 0xc002d54d00, 0x2535b01, 0xc002d54d00)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/service/crud.go:109 +0xdd3
github.com/lyraproj/wfe/wfe.(*resource).Run(0xc002123200, 0x25555c0, 0xc003213800, 0x25618c0, 0xc002d54d00, 0x25451e0, 0xc003a857c0)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/resource.go:55 +0x5f
github.com/lyraproj/wfe/wfe.(*workflowEngine).runActivity(0xc003213260, 0x25555c0, 0xc003213800, 0xc001a916e0)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/workflowengine.go:417 +0x3da
github.com/lyraproj/wfe/wfe.(*workflowEngine).activityWorker(0xc003213260, 0x25555c0, 0xc003213800, 0x6)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/workflowengine.go:391 +0x91
github.com/lyraproj/wfe/wfe.(*workflowEngine).Run.func2(0x25555c0, 0xc003213800)
	/Users/Mark/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190313115747-595a82b1cd4f/wfe/workflowengine.go:317 +0x4a
github.com/lyraproj/pcore/px.Fork.func1(0x25555c0, 0xc0003771a0, 0xc001c724c0)
	/Users/Mark/code/pcore/px/context.go:166 +0xb7
created by github.com/lyraproj/pcore/px.Fork
	/Users/Mark/code/pcore/px/context.go:161 +0x53
```

</details>
